function lc-run --description "Run LeetCode solution with test cases"
    if contains -- --help $argv; or contains -- -h $argv
        echo "Usage: lc-run [FILE]"
        echo ""
        echo "Run LeetCode solution with @test cases."
        echo "Detects language by extension (.scala / .rs)."
        echo "If no file given, uses the last argument or prompts."
        echo ""
        echo "Test format (in comments):"
        echo "  Scala: // @test methodName(args) = expected"
        echo "  Rust:  // @test method_name(args) = expected"
        echo ""
        echo "Examples:"
        echo "  lc-run solution.scala"
        echo "  lc-run solution.rs"
        return 0
    end

    set -l file $argv[1]
    if test -z "$file"
        echo "Usage: lc-run <file.scala|file.rs>"
        return 1
    end

    if not test -f "$file"
        echo "File not found: $file"
        return 1
    end

    set -l ext (string match -r '\.[^.]+$' $file | string sub -s 2)

    switch $ext
        case scala
            _lc_run_scala $file
        case rs
            _lc_run_rust $file
        case '*'
            echo "Unsupported extension: $ext (use .scala or .rs)"
            return 1
    end
end

function _lc_run_scala
    set -l file $argv[1]
    set -l dir (dirname $file)
    set -l tmpdir /tmp/lc-run
    mkdir -p $tmpdir

    # Find LeetCode.scala library
    set -l lib ""
    if test -f "$dir/LeetCode.scala"
        set lib "$dir/LeetCode.scala"
    else if test -f ~/dotfiles-mac/leetcode/LeetCode.scala
        set lib ~/dotfiles-mac/leetcode/LeetCode.scala
    end

    # Extract @test lines
    set -l tests (grep '// @test ' $file | sed 's|^.*// @test ||')
    if test (count $tests) -eq 0
        # No tests — just compile and run (user has their own main)
        set -l cmd "scala"
        if test -n "$lib"
            set cmd $cmd $lib
        end
        set cmd $cmd $file
        echo "No @test found — running directly..."
        $cmd
        return $status
    end

    # Extract package name (if any)
    set -l pkg (grep '^package ' $file | head -1 | sed 's/^package //')

    # Extract method name and generate runner
    set -l runner "$tmpdir/Runner.scala"

    echo "// Auto-generated by lc-run" >$runner
    if test -n "$pkg"
        echo "import $pkg.Solution" >>$runner
    end
    echo "@main def run(): Unit =" >>$runner
    echo "  var passed = 0" >>$runner
    echo "  var failed = 0" >>$runner
    echo "  val total = "(count $tests) >>$runner
    echo "" >>$runner

    set -l i 0
    for test_line in $tests
        set i (math $i + 1)

        # Parse: methodName(args) = expected
        set -l method_call (echo $test_line | sed 's| *= *[^=]*$||')
        set -l expected (echo $test_line | sed 's|^.*= *||')

        echo "  // Test $i" >>$runner
        echo "  try" >>$runner
        echo "    val result = Solution.$method_call" >>$runner
        echo "    val exp = $expected" >>$runner
        echo "    val resultStr = LC.fmt(result)" >>$runner
        echo "    val expStr = LC.fmt(exp)" >>$runner
        echo "    if resultStr == expStr then" >>$runner
        echo "      println(s\"Test $i: ✓  \$resultStr\")" >>$runner
        echo "      passed += 1" >>$runner
        echo "    else" >>$runner
        echo "      println(s\"Test $i: ✗  got \$resultStr, expected \$expStr\")" >>$runner
        echo "      failed += 1" >>$runner
        echo "  catch case e: Exception =>" >>$runner
        echo "    println(s\"Test $i: ✗  \${e.getMessage}\")" >>$runner
        echo "    failed += 1" >>$runner
        echo "" >>$runner
    end

    echo "  println(s\"── \$passed/\$total passed ──\")" >>$runner

    # Compile and run
    set -l cmd scala
    if test -n "$lib"
        set cmd $cmd $lib
    end
    set cmd $cmd $file $runner

    $cmd
    return $status
end

function _lc_run_rust
    set -l file $argv[1]
    set -l tmpdir /tmp/lc-run
    mkdir -p $tmpdir

    # Extract @test lines
    set -l tests (grep '// @test ' $file | sed 's|^.*// @test ||')

    set -l runner "$tmpdir/lc_runner.rs"

    # ListNode & TreeNode definitions
    echo "// Auto-generated by lc-run" >$runner
    echo "#![allow(unused_imports, dead_code)]" >>$runner
    echo "#[derive(Debug, Clone, PartialEq, Eq)]" >>$runner
    echo "pub struct ListNode { pub val: i32, pub next: Option<Box<ListNode>> }" >>$runner
    echo "impl ListNode {" >>$runner
    echo "  #[inline] fn new(val: i32) -> Self { ListNode { val, next: None } }" >>$runner
    echo "}" >>$runner
    echo "" >>$runner
    echo "#[derive(Debug, Clone, PartialEq, Eq)]" >>$runner
    echo "pub struct TreeNode { pub val: i32, pub left: Option<Rc<RefCell<TreeNode>>>, pub right: Option<Rc<RefCell<TreeNode>>> }" >>$runner
    echo "use std::rc::Rc;" >>$runner
    echo "use std::cell::RefCell;" >>$runner
    echo "use std::collections::*;" >>$runner
    echo "" >>$runner
    echo "struct Solution;" >>$runner
    echo "" >>$runner

    # Include user code (strip "impl Solution" wrapper)
    cat $file | grep -v '// @test' >>$runner

    echo "" >>$runner
    echo "fn main() {" >>$runner

    if test (count $tests) -eq 0
        echo '    println!("No @test found");' >>$runner
    else
        set -l i 0
        echo "    let mut passed = 0;" >>$runner
        echo "    let mut failed = 0;" >>$runner
        for test_line in $tests
            set i (math $i + 1)
            set -l method_call (echo $test_line | sed 's| *= *[^=]*$||')
            set -l expected (echo $test_line | sed 's|^.*= *||')

            echo "    {" >>$runner
            echo "        let result = Solution::$method_call;" >>$runner
            echo "        let expected = $expected;" >>$runner
            echo "        if result == expected {" >>$runner
            echo "            println!(\"Test $i: ✓  {:?}\", result);" >>$runner
            echo "            passed += 1;" >>$runner
            echo "        } else {" >>$runner
            echo "            println!(\"Test $i: ✗  got {:?}, expected {:?}\", result, expected);" >>$runner
            echo "            failed += 1;" >>$runner
            echo "        }" >>$runner
            echo "    }" >>$runner
        end
        echo "    println!(\"── {}/{} passed ──\", passed, passed + failed);" >>$runner
    end

    echo "}" >>$runner

    # Compile and run
    if rustc $runner -o $tmpdir/lc_test 2>&1
        $tmpdir/lc_test
    end
    return $status
end
